name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chat
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10

    env:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONDONTWRITEBYTECODE: 1

      # DB env read by your Django settings
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: "5432"
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      # IMPORTANT: point at the redis *service* hostname
      REDIS_URL: redis://redis:6379/1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-asyncio pytest-cov

      - name: Wait for services
        env:
          PGPASSWORD: postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do sleep 1; done
          until redis-cli -h redis ping; do sleep 1; done

      - name: Migrate
        run: python manage.py migrate --noinput

      - name: Run tests
        run: pytest -q
