name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: chat
          POSTGRES_PASSWORD: chat
          POSTGRES_DB: chat
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U chat -d chat"
          --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports: ["6379:6379"]
    env:
      DATABASE_URL: postgres://chat:chat@localhost:5432/chat
      REDIS_URL: redis://localhost:6379/1
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt
      - run: python manage.py migrate --noinput
      - run: pytest --maxfail=1 --disable-warnings -q

