name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: chat
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d chat"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONDONTWRITEBYTECODE: "1"
      # Tell Django (via settings_local) how to reach the CI Postgres service:
      POSTGRES_HOST: postgres
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Redis in CI:
      REDIS_URL: redis://redis:6379/1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system deps for psycopg2
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Make static dir (silence warning)
        run: mkdir -p static

      - name: Django checks
        run: python manage.py check --deploy --fail-level WARNING || true

      - name: Migrate
        run: python manage.py migrate --noinput

      - name: Run tests
        run: pytest -q
